.TH "Graph< V >::CustomCompare" 3 "Version 1" "Roomba Controller Dashboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graph< V >::CustomCompare
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Graph\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBoperator()\fP (\fBconst\fP \fBpair\fP &\fBfirst\fP, \fBconst\fP \fBpair\fP &\fBsecond\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP \fBV\fP>
.br
struct Graph< V >::CustomCompare"
.PP
Definition at line \fB20\fP of file \fBGraph\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBV\fP > \fBbool\fP \fBGraph\fP< \fBV\fP >::CustomCompare::operator() (\fBconst\fP \fBpair\fP & first, \fBconst\fP \fBpair\fP & second)\fR [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBGraph\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Roomba Controller Dashboard from the source code\&.
