.TH "/home/calebk/Documents/coding/RoombaController/src/HoleManager.hpp" 3 "Version 1" "Roomba Controller Dashboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/calebk/Documents/coding/RoombaController/src/HoleManager.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Hole\&.hpp'\fP
.br
\fR#include 'util\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHoleManager\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBsideLength\fP   0\&.6096"
.br
.ti -1c
.RI "#define \fBMEASUREMENT_WIDTH\fP   0\&.05"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MEASUREMENT_WIDTH   0\&.05"

.PP
Definition at line \fB12\fP of file \fBHoleManager\&.hpp\fP\&.
.SS "#define sideLength   0\&.6096"
Created by Caleb Kugel 11/15/2024 
.PP
Definition at line \fB11\fP of file \fBHoleManager\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roomba Controller Dashboard from the source code\&.
