.TH "/home/calebk/Documents/coding/RoombaController/src/Hole.hpp" 3 "Version 1" "Roomba Controller Dashboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/calebk/Documents/coding/RoombaController/src/Hole.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'vector'\fP
.br
\fR#include <memory>\fP
.br
\fR#include 'Pose2D\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <ostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHole\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHOLE_SIZE\fP   69\&.06"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HOLE_SIZE   69\&.06"
Made by Caleb Kugel on 11/15/2024 
.PP
Definition at line \fB14\fP of file \fBHole\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roomba Controller Dashboard from the source code\&.
