.TH "/home/calebk/Documents/coding/RoombaController/src/Hole.cpp" 3 "Version 1" "Roomba Controller Dashboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/calebk/Documents/coding/RoombaController/src/Hole.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include 'Hole\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBHole\fP &hole)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream & operator<< (std::ostream & os, const \fBHole\fP & hole)"
Override output stream for printing 
.PP
\fBParameters\fP
.RS 4
\fIos\fP output stream 
.br
\fIhole\fP the hole to print 
.RE
.PP
\fBReturns\fP
.RS 4
the hole printed in the out stream 
.RE
.PP

.PP
Definition at line \fB373\fP of file \fBHole\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roomba Controller Dashboard from the source code\&.
