.TH "Move" 3 "Version 1" "Roomba Controller Dashboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Move
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBquantity\fP"
.br
.ti -1c
.RI "\fBMovementType\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB45\fP of file \fBmain\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double Move::quantity"

.PP
Definition at line \fB46\fP of file \fBmain\&.cpp\fP\&.
.SS "\fBMovementType\fP Move::type"

.PP
Definition at line \fB47\fP of file \fBmain\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Roomba Controller Dashboard from the source code\&.
