.TH "Node< V >" 3 "Version 1" "Roomba Controller Dashboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node< V >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Node\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (V data)"
.br
.ti -1c
.RI "V \fBgetData\fP ()"
.br
.ti -1c
.RI "void \fBSetData\fP (V newData)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename V>
.br
class Node< V >"Represents a node in a graph\&. Really just a wrapped for V 
.PP
\fBParameters\fP
.RS 4
\fIV\fP The data that the node encapsulates 
.RE
.PP

.PP
Definition at line \fB17\fP of file \fBNode\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename V > \fBNode\fP< V >\fB::Node\fP (V data)"
Constructs a node from given data 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP to construct the node from 
.RE
.PP

.PP
Definition at line \fB9\fP of file \fBNode\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename V > V \fBNode\fP< V >::getData ()"

.PP
\fBReturns\fP
.RS 4
the data stored in the node 
.RE
.PP

.PP
Definition at line \fB14\fP of file \fBNode\&.cpp\fP\&.
.SS "template<typename V > void \fBNode\fP< V >::SetData (V newData)"
sets the data we store in the node 
.PP
\fBParameters\fP
.RS 4
\fInewData\fP new data to replace current data with 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBNode\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Roomba Controller Dashboard from the source code\&.
