.TH "/home/calebk/Documents/coding/RoombaController/src/util.hpp" 3 "Version 1" "Roomba Controller Dashboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/calebk/Documents/coding/RoombaController/src/util.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cmath>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBorientation\fP (double px2, double py, double qx, double qy, double rx, double ry)"
.br
.ti -1c
.RI "bool \fBonSegment\fP (double px, double py, double qx, double qy, double rx, double ry)"
.br
.ti -1c
.RI "bool \fBdoIntersect\fP (double p1x, double p1y, double q1x, double q1y, double p2x, double p2y, double q2x, double q2y)"
.br
.ti -1c
.RI "bool \fBlineIntersectsRectangle\fP (double cx1, double cy1, double cx2, double cy2, double rx1, double ry1, double rx2, double ry2, double rx3, double ry3, double rx4, double ry4)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool doIntersect (double p1x, double p1y, double q1x, double q1y, double p2x, double p2y, double q2x, double q2y)"

.PP
Definition at line \fB18\fP of file \fButil\&.cpp\fP\&.
.SS "bool lineIntersectsRectangle (double cx1, double cy1, double cx2, double cy2, double rx1, double ry1, double rx2, double ry2, double rx3, double ry3, double rx4, double ry4)"

.PP
Definition at line \fB46\fP of file \fButil\&.cpp\fP\&.
.SS "bool onSegment (double px, double py, double qx, double qy, double rx, double ry)"

.PP
Definition at line \fB13\fP of file \fButil\&.cpp\fP\&.
.SS "double orientation (double px, double py, double qx, double qy, double rx, double ry)"
Created by Caleb Kugel 11/21/2024 
.PP
Definition at line \fB7\fP of file \fButil\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roomba Controller Dashboard from the source code\&.
